apiVersion: v1
kind: Service
metadata:
  name: aiqr-backend-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: aiqr-backend-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
